saldo = 200

saque = 100

print(saldo == saque) # saldo igual a...

print(saldo != saque) # saldo diferente de...

print(saldo > saque) # saldo maior que...

print(saldo < saque) # saldo menor que...

print(saldo >= saque) # saldo mair ou igual a...

print(saldo <= saque) # saldo menor ou igual a...